=== w4rgrum/terraschema/test/expected/simple-types/schema-nullable-all.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"additionalProperties": true,
	"properties": {
		"a_bool": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"title": "boolean",
					"type": "boolean"
				}
			],
			"default": false,
			"description": "This is a boolean",
			"title": "a_bool: Select a type"
		},
		"a_list": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"items": {
						"type": "string"
					},
					"title": "array",
					"type": "array"
				}
			],
			"default": [
				"a",
				"b",
				"c"
			],
			"description": "This is a list of strings",
			"title": "a_list: Select a type"
		},
		"a_list_of_any": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"items": {
						"anyOf": [
							{
								"additionalProperties": true,
								"title": "object",
								"type": "object"
							},
							{
								"title": "array",
								"type": "array"
							},
							{
								"title": "string",
								"type": "string"
							},
							{
								"title": "number",
								"type": "number"
							},
							{
								"title": "boolean",
								"type": "boolean"
							},
							{
								"title": "null",
								"type": "null"
							}
						]
					},
					"title": "array",
					"type": "array"
				}
			],
			"default": [
				"a",
				"b",
				"c"
			],
			"description": "This is a list of any",
			"title": "a_list_of_any: Select a type"
		},
		"a_map_of_any": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"additionalProperties": {
						"anyOf": [
							{
								"additionalProperties": true,
								"title": "object",
								"type": "object"
							},
							{
								"title": "array",
								"type": "array"
							},
							{
								"title": "string",
								"type": "string"
							},
							{
								"title": "number",
								"type": "number"
							},
							{
								"title": "boolean",
								"type": "boolean"
							},
							{
								"title": "null",
								"type": "null"
							}
						]
					},
					"title": "object",
					"type": "object"
				}
			],
			"default": {
				"a": "a",
				"b": "b",
				"c": "c"
			},
			"description": "This is a map of any",
			"title": "a_map_of_any: Select a type"
		},
		"a_map_of_strings": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"additionalProperties": {
						"type": "string"
					},
					"title": "object",
					"type": "object"
				}
			],
			"default": {
				"a": "a",
				"b": "b",
				"c": "c"
			},
			"description": "This is a map of strings",
			"title": "a_map_of_strings: Select a type"
		},
		"a_nullable_string": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"title": "string",
					"type": "string"
				}
			],
			"description": "This is a nullable string",
			"title": "a_nullable_string: Select a type"
		},
		"a_number": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"title": "number",
					"type": "number"
				}
			],
			"description": "This is a number",
			"title": "a_number: Select a type"
		},
		"a_set": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"items": {
						"type": "string"
					},
					"title": "array",
					"type": "array",
					"uniqueItems": true
				}
			],
			"default": [
				"a",
				"b",
				"c"
			],
			"description": "This is a set of strings",
			"title": "a_set: Select a type"
		},
		"a_set_of_any": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"items": {
						"anyOf": [
							{
								"additionalProperties": true,
								"title": "object",
								"type": "object"
							},
							{
								"title": "array",
								"type": "array"
							},
							{
								"title": "string",
								"type": "string"
							},
							{
								"title": "number",
								"type": "number"
							},
							{
								"title": "boolean",
								"type": "boolean"
							},
							{
								"title": "null",
								"type": "null"
							}
						]
					},
					"title": "array",
					"type": "array",
					"uniqueItems": true
				}
			],
			"default": [
				"a",
				"b",
				"c"
			],
			"description": "This is a set of any",
			"title": "a_set_of_any: Select a type"
		},
		"a_string": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"title": "string",
					"type": "string"
				}
			],
			"default": "a string",
			"description": "This is a string",
			"title": "a_string: Select a type"
		},
		"a_tuple": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"items": [
						{
							"type": "string"
						},
						{
							"type": "number"
						},
						{
							"type": "boolean"
						}
					],
					"maxItems": 3,
					"minItems": 3,
					"title": "array",
					"type": "array"
				}
			],
			"default": [
				"a",
				1,
				true
			],
			"description": "This is a tuple",
			"title": "a_tuple: Select a type"
		},
		"a_variable_in_another_file": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"title": "string",
					"type": "string"
				}
			],
			"default": "",
			"description": "a string",
			"title": "a_variable_in_another_file: Select a type"
		},
		"an_any_as_boolean": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": true,
			"description": "This is an any",
			"title": "an_any_as_boolean: Select a type"
		},
		"an_any_as_list": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": [],
			"description": "This is an any",
			"title": "an_any_as_list: Select a type"
		},
		"an_any_as_map": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": {},
			"description": "This is an any",
			"title": "an_any_as_map: Select a type"
		},
		"an_any_as_number": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": 1,
			"description": "This is an any",
			"title": "an_any_as_number: Select a type"
		},
		"an_any_as_string": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": "default",
			"description": "This is an any",
			"title": "an_any_as_string: Select a type"
		},
		"an_object": {
			"anyOf": [
				{
					"title": "null",
					"type": "null"
				},
				{
					"additionalProperties": true,
					"properties": {
						"a": {
							"type": "string"
						},
						"b": {
							"type": "number"
						},
						"c": {
							"type": "boolean"
						}
					},
					"required": [
						"a",
						"b",
						"c"
					],
					"title": "object",
					"type": "object"
				}
			],
			"default": {
				"a": "a",
				"b": 1,
				"c": true
			},
			"description": "This is an object",
			"title": "an_object: Select a type"
		},
		"an_unspecified_as_boolean": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": true,
			"description": "This is an unspecified",
			"title": "an_unspecified_as_boolean: Select a type"
		},
		"an_unspecified_as_list": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": [],
			"description": "This is an unspecified",
			"title": "an_unspecified_as_list: Select a type"
		},
		"an_unspecified_as_map": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": {},
			"description": "This is an unspecified",
			"title": "an_unspecified_as_map: Select a type"
		},
		"an_unspecified_as_number": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": 1,
			"description": "This is an unspecified",
			"title": "an_unspecified_as_number: Select a type"
		},
		"an_unspecified_as_string": {
			"anyOf": [
				{
					"additionalProperties": true,
					"title": "object",
					"type": "object"
				},
				{
					"title": "array",
					"type": "array"
				},
				{
					"title": "string",
					"type": "string"
				},
				{
					"title": "number",
					"type": "number"
				},
				{
					"title": "boolean",
					"type": "boolean"
				},
				{
					"title": "null",
					"type": "null"
				}
			],
			"default": "default",
			"description": "This is an unspecified",
			"title": "an_unspecified_as_string: Select a type"
		}
	},
	"required": [
		"a_nullable_string",
		"a_number"
	],
	"type": "object"
}

=== w4rgrum/terraschema/test/expected/simple-types/sample-input/test-input-null.json
{
    "$schema": "../schema.json",
    "a_bool": null,
    "a_list": null,
    "a_list_of_any": null,
    "a_map_of_any": null,
    "a_map_of_strings": null,
    "a_nullable_string": null,
    "a_number": null,
    "a_set_of_any": null,
    "a_set": null,
    "a_string": null,
    "a_tuple": null,
    "a_variable_in_another_file": null,
    "an_any_as_boolean": null,
    "an_any_as_list": null,
    "an_any_as_map": null,
    "an_any_as_number": null,
    "an_any_as_string": null,
    "an_object": null,
    "an_unspecified_as_boolean": null,
    "an_unspecified_as_list": null,
    "an_unspecified_as_map": null,
    "an_unspecified_as_number": null,
    "an_unspecified_as_string": null
}

=== w4rgrum/terraschema/test/expected/simple-types/variables.json
{
	"a_bool": {
		"default": false,
		"description": "This is a boolean",
		"type": "bool"
	},
	"a_list": {
		"default": [
			"a",
			"b",
			"c"
		],
		"description": "This is a list of strings",
		"type": [
			"list",
			"string"
		]
	},
	"a_list_of_any": {
		"default": [
			"a",
			"b",
			"c"
		],
		"description": "This is a list of any",
		"type": [
			"list",
			"dynamic"
		]
	},
	"a_map_of_any": {
		"default": {
			"a": "a",
			"b": "b",
			"c": "c"
		},
		"description": "This is a map of any",
		"type": [
			"map",
			"dynamic"
		]
	},
	"a_map_of_strings": {
		"default": {
			"a": "a",
			"b": "b",
			"c": "c"
		},
		"description": "This is a map of strings",
		"type": [
			"map",
			"string"
		]
	},
	"a_nullable_string": {
		"default": null,
		"description": "This is a nullable string",
		"nullable": true,
		"type": "string"
	},
	"a_number": {
		"default": null,
		"description": "This is a number",
		"type": "number"
	},
	"a_set": {
		"default": [
			"a",
			"b",
			"c"
		],
		"description": "This is a set of strings",
		"type": [
			"set",
			"string"
		]
	},
	"a_set_of_any": {
		"default": [
			"a",
			"b",
			"c"
		],
		"description": "This is a set of any",
		"type": [
			"set",
			"dynamic"
		]
	},
	"a_string": {
		"default": "a string",
		"description": "This is a string",
		"type": "string"
	},
	"a_tuple": {
		"default": [
			"a",
			1,
			true
		],
		"description": "This is a tuple",
		"type": [
			"tuple",
			[
				"string",
				"number",
				"bool"
			]
		]
	},
	"a_variable_in_another_file": {
		"default": "",
		"description": "a string",
		"type": "string"
	},
	"an_any_as_boolean": {
		"default": true,
		"description": "This is an any",
		"type": "dynamic"
	},
	"an_any_as_list": {
		"default": [],
		"description": "This is an any",
		"type": "dynamic"
	},
	"an_any_as_map": {
		"default": {},
		"description": "This is an any",
		"type": "dynamic"
	},
	"an_any_as_number": {
		"default": 1,
		"description": "This is an any",
		"type": "dynamic"
	},
	"an_any_as_string": {
		"default": "default",
		"description": "This is an any",
		"type": "dynamic"
	},
	"an_object": {
		"default": {
			"a": "a",
			"b": 1,
			"c": true
		},
		"description": "This is an object",
		"type": [
			"object",
			{
				"a": "string",
				"b": "number",
				"c": "bool"
			}
		]
	},
	"an_unspecified_as_boolean": {
		"default": true,
		"description": "This is an unspecified",
		"type": "any"
	},
	"an_unspecified_as_list": {
		"default": [],
		"description": "This is an unspecified",
		"type": "any"
	},
	"an_unspecified_as_map": {
		"default": {},
		"description": "This is an unspecified",
		"type": "any"
	},
	"an_unspecified_as_number": {
		"default": 1,
		"description": "This is an unspecified",
		"type": "any"
	},
	"an_unspecified_as_string": {
		"default": "default",
		"description": "This is an unspecified",
		"type": "any"
	}
}
